. "$HOME/.cargo/env"
export EDITOR="nvim"
export KUBE_EDITOR="$EDITOR"
export GOPATH="$HOME/.go"
export GOBIN="$GOPATH/bin"
export GOROOT=/usr/local/go
export SDKMAN_DIR="$HOME/.sdkman"
export NVM_DIR="$HOME/.nvm"
export PATH="/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/opt/openssl@3/bin:/usr/local/sbin:${GOROOT}/bin:${GOPATH}/bin:${JAVA_HOME}/bin:$PATH"
